apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-uum4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-uum4
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-uum4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-uum4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-uum4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jkos-tenant/status-quarkus-io/statusquarkusio-uum4@sha256:9f193abaedc0e70225bcbecc28c17c6bbe8c15b635e6877f0f4161a77b65d422
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
